//! Procedural macro helpers.

mod bitset;

/// Generates a bitset representation of a given enum.
///
/// This can be used to concisely represent a set of multiple error variants without having to
/// resort to list allocation.
///
/// # Panics
///
/// If [`syn`] fails to parse the macro input.
///
/// # Example
///
/// ```rust
/// # use macro_derive::*;
/// #[derive(BitSet, PartialEq, Eq, Debug)]
/// #[repr(u8)]
/// enum Error {
///     UserError,
///     ServerError,
/// }
///
/// // `ErrorBitSet` is generated by `#[derive(BitSet)]`
/// let mut bitset = ErrorBitSet::new();
///
/// // New enum variants are recorded using `add` and checked for with `contains`.
/// bitset.add(Error::UserError);
/// assert!(bitset.contains(Error::UserError));
///
/// bitset.add(Error::ServerError);
/// assert!(bitset.contains(Error::ServerError));
///
/// // It is possible to iterate over all enum variants stored in a bitset.
/// // This is the preferred way to process errors.
/// let mut iter = bitset.iter();
///
/// assert_eq!(iter.next().unwrap(), Error::UserError);
/// assert_eq!(iter.next().unwrap(), Error::ServerError);
/// assert_eq!(iter.next(), None);
/// ```
///
/// # Codegen
///
/// The following is an example of the kind of output you can expect from this macro. Keep in mind
/// that the resulting bitset is baked into the surrounding module and does not re-use any generic
/// implementation. This can lead to quite a bit of codegen if this macro is used often.
///
/// ```rust
/// # enum Error {
/// #     UserError,
/// #     ServerError,
/// # }
/// #
/// struct ErrorBitSet(u8);
/// impl ErrorBitSet {
///     fn new() -> Self {
///         Self(0)
///     }
///     fn add(&mut self, err: Error) {
///         self.0 |= 1 << (err as u8);
///     }
///
///     fn contains(&self, err: Error) -> bool {
///         self.0 & 1 << (err as u8) > 0
///     }
///
///     fn len(&self) -> usize {
///         self.0.count_ones() as usize
///     }
///
///     fn is_empty(&self) -> bool {
///         self.len() == 0
///     }
///
///     fn iter(&self) -> ErrorBitSetIter {
///         ErrorBitSetIter {
///             bitset: self.0,
///             index: 0,
///         }
///     }
/// }
///
/// impl IntoIterator for ErrorBitSet {
///     type Item = Error;
///     type IntoIter = ErrorBitSetIter;
///     fn into_iter(self) -> ErrorBitSetIter {
///         self.iter()
///     }
/// }
///
/// struct ErrorBitSetIter {
///     bitset: u8,
///     index: u8,
/// }
///
/// impl Iterator for ErrorBitSetIter {
///     type Item = Error;
///     fn next(&mut self) -> Option<Error> {
///         while self.index < u8::BITS as u8 {
///             let check_occurrence = self.bitset & 1 << self.index;
///             self.index += 1;
///
///             if check_occurrence > 0 {
///                 let index = check_occurrence.trailing_zeros() as u8;
///                 match index {
///                     0u8 => return Some(Error::UserError),
///                     1u8 => return Some(Error::ServerError),
///                     _ => unreachable!(),
///                 }
///             }
///         }
///
///         None
///     }
/// }
/// ```
#[proc_macro_derive(BitSet)]
pub fn bitset_derive(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let ast = match syn::parse(input) {
        Ok(ast) => ast,
        Err(err) => panic!("Failed to parse macro input: {err}"),
    };

    match bitset::impl_bitset_derive(&ast) {
        Ok(token_stream) => token_stream,
        Err(err) => err.into_compile_error().into(),
    }
}
