[package]
name = "http-server"
version = "0.1.0"
edition = "2024"
rust-version = "1.96"

[lib]
path = "./src/lib.rs"

[[bin]]
name = "http-server"
path = "./src/main.rs"

[dependencies]
# Logging
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

# Parsing
memchr = "2.8.3"

[dev-dependencies]
rstest = "0.26.1"
pretty_assertions = "1.4.1"
