name: "opencode"
services:
  opencode:
    build: .
    env_file: ".env"

    stdin_open: true
    tty: true

    volumes:
      - .:/work

    environment:
      UNSLOTH_API_KEY: "${UNSLOTH_API_KEY}"

    # Networking

    network_mode: bridge

    extra_hosts:
      - "host.docker.internal:192.168.1.47"
