[package]
name = "http_1"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
# http
http_core.workspace = true

# Logging
tracing.workspace = true
tracing-subscriber.workspace = true

# Parsing
memchr.workspace = true

[[example]]
name = "server"
doc-scrape-examples = true
